### ISSUE TITLE
Looking forward the code!!!!

### ISSUE THREAD

**Issue by WJ-Lai** [saic-mdal/HiDT#1]
Hi! 

Congratulations for the great work!

The results in the paper were amazing!

1. Could you please tell me when can you publish the code and the training dataset？

2. If the code is not ready now, could you please tell me how can I download the dataset?

Thanks!

**Comment by denkorzh** [comment]
Hello, @WJ-Lai. We will publish the code as soon as we resolve all the IP issues.
Unfortunately, the collected dataset of landscape images is sensitive and will not be shared.
Nevertheless, the WikiArt dataset is publicly available.

**Comment by geraltsnake** [comment]
I'm really looking forward to this technology. The sample images are so amazing and It could beat the photoshop!!

**Comment by WJ-Lai** [comment]
> Hello, @WJ-Lai. We will publish the code as soon as we resolve all the IP issues.
> Unfortunately, the collected dataset of landscape images is sensitive and will not be shared.
> Nevertheless, the WikiArt dataset is publicly available.

Thanks for your replay! Could you please tell me an approximate time? Maybe a month or?

That's is a fabulous work!

**Comment by MasterScrat** [comment]
Very nice work :D Please comment on/close this issue when the code is published so people who subscribe get pinged!

**Comment by Dariusz1989** [comment]
+1 from me too. Looks amazing so far!

**Comment by Johnson-yue** [comment]
me，too

**Comment by ttdung997** [comment]
i'm looking forward it, too
Thank you again for everything you’ve done @denkorzh

**Comment by nikolay-n** [comment]
This is a commercial functionality, it is unlikely to be published soon.

**Comment by howkj1** [comment]
> This is a commercial functionality, it is unlikely to be published soon.

It says in the very first lines of the ReadMe for this repo 
quote "HiDT Code will be released soon. Stay tuned!"

see @denkorzh comment https://github.com/saic-mdal/HiDT/issues/1#issuecomment-609597343 for more info

**Comment by connorgreenwell** [comment]
Now that CVPR has passed, any updated on whether or not code will be released? Looking forward to it!

**Comment by jakubLangr** [comment]
+1
