### ISSUE TITLE
How can I get the training data?

### ISSUE THREAD

**Issue by Sweetclover** [saic-mdal/HiDT#3]

**Comment by mindplay-dk** [comment]
See #1.

**Comment by Sweetclover** [comment]
How can I train the network

**Comment by belkakari** [comment]
As for now, we have released only the inference scripts and pretrained weights for two datasets: the one we have collected from Flickr (which we will not publish due to the licensing issues) and [WikiArt](https://github.com/cs-chan/ArtGAN/tree/master/WikiArt%20Dataset) dataset, which is opensourced

**Comment by Sweetclover** [comment]
I'm very looking forward to your training code!
