### ISSUE TITLE
Hi!Why the skip-dim is only 5?

### ISSUE THREAD

**Issue by 2165998** [saic-mdal/HiDT#9]
In general, the skip-dim is the same as the output-dim of conv to make full use of low-dim feature map.
So i guess, even if the G use Adain norm block to move out the original style of skip-block, it is not enough if we use the full skip-dim.
Thanks for your help~

**Comment by denkorzh** [comment]
Hi! We use dense skip-connections, i.e. concatenates the features from the encoder to the features of the decoder, not just sum them up. That is why we may choose an arbitrary number of channels as a skip-connection. In our experiments, we have found that 5 channels are enough and the usage of all the features is redundant for our model.

**Comment by 2165998** [comment]
Oh I see.Yes, we usually use concatenate operation in the skip-connection.
Thanks for your reply~
